spring:
  datasource:
    url: jdbc:mysql://db:3306/arbeitmate?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: arbeitmate
    password: arbeitmate_pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update